apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aggregator-svc
  labels:
    app: aggregator-svc
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aggregator-svc
        tier: backend
    spec:
      containers:
      - name: aggregator-svc
        image: "stiller/tweeteranalyzerdemo_aggregator:v2"

---

apiVersion: v1
kind: Service
metadata:
  name: aggregator-svc
  labels:
    app: aggregator-svc
    tier: backend
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: aggregator-svc
    tier: backend