apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: middleware
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: middleware
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.7-management
        ports:
        - containerPort: 15672
        - containerPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: middleware
spec:
  type: ClusterIP
  ports:
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "5672"
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
    tier: middleware
