apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    tier: middleware
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: middleware
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: middleware
spec:
  type: ClusterIP
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: middleware
