apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result-svc
  labels:
    app: result-svc
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result-svc
        tier: backend
    spec:
      containers:
      - name: result-svc
        image: "stiller/tweeteranalyzerdemo_result:v2"
        ports:
        - containerPort: 80
            
---

apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    app: result-svc
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
  selector:
    app: result-svc
    tier: backend