apiVersion: v1
kind: Secret
metadata:
  name: twitter-secrets
type: Opaque
data:
  TwitterConsumerKey: <fill in with your twitter's application key>
  TwitterConsumerSecret: <fill in with your twitter's application secret>
  TwitterAccessToken: <fill in with your twitter's application token>
  TwitterAccessTokenSecret: <fill in with your twitter's application token secret>
  TextAnalyticsApiKey: <fill in with your azure's cognitive-service api key>